# Generated by Django 4.1.2 on 2022-10-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
